/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mHtlsWXw9ys
 */
import { useState } from "react";
import { Button } from "~/@/components/ui/button"
import { CardContent, Card } from "~/@/components/ui/card"
import { PaginationPrevious, PaginationItem, PaginationLink, PaginationEllipsis, PaginationNext, PaginationContent, Pagination } from "~/@/components/ui/pagination"
import { useNavigate } from 'react-router-dom';  // Import useNavigate hook

export function Dashboard() {
  const [hovered, setHovered] = useState(false)
  const navigate = useNavigate();  // Initialize the useNavigate hook

  const startNewProject = () => {
    navigate('/edit');
  };

  const setHover = () => {
    setHovered(!hovered)
  };

  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      <header className="flex items-center justify-between p-12">
        <div className="flex items-center">
          <img alt="Logo" className="h-24 w-auto" src="./images/logo.png" />
        </div>
        <button onClick={startNewProject} onMouseEnter={setHover} onMouseLeave={setHover}>
          { hovered ? 
            <img className="h-10" src="./images/button.png"/> :
            <img className="h-10" src="./images/button2.png"/> 
          }
          {/* <svg
            className="h-6 w-6"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M12 6v6m0 0v6m0-6h6m-6 0H6" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} />
          </svg> */}
        </button>
      </header>
      <main className="flex-1 flex flex-wrap justify-start overflow-hidden p-6">
        <div className="w-full sm:w-1/2 lg:w-1/3 p-4">
          <Card className="pt-5">
            <CardContent className="opacity-0 hover:opacity-100 transition-opacity duration-300">
              <h2 className="text-xl font-semibold mb-2">First Post</h2>
              <p className="text-gray-600 dark:text-gray-300">Author: John Doe</p>
              <p className="text-gray-600 dark:text-gray-300">Date: Jan 20, 2024</p>
              <div className="mt-4 flex space-x-2">
                <Button size="sm" variant="outline">
                  Edit
                </Button>
                <Button size="sm" variant="outline">
                  Delete
                </Button>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="w-full sm:w-1/2 lg:w-1/3 p-4">
          <Card className="pt-5">
            <CardContent className="opacity-0 hover:opacity-100 transition-opacity duration-300">
              <h2 className="text-xl font-semibold mb-2">Second Post</h2>
              <p className="text-gray-600 dark:text-gray-300">Author: Jane Doe</p>
              <p className="text-gray-600 dark:text-gray-300">Date: Jan 21, 2024</p>
              <div className="mt-4 flex space-x-2">
                <Button size="sm" variant="outline">
                  Edit
                </Button>
                <Button size="sm" variant="outline">
                  Delete
                </Button>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="w-full sm:w-1/2 lg:w-1/3 p-4">
          <Card className="pt-5">
            <CardContent className="opacity-0 hover:opacity-100 transition-opacity duration-300">
              <h2 className="text-xl font-semibold mb-2">Third Post</h2>
              <p className="text-gray-600 dark:text-gray-300">Author: Alex Smith</p>
              <p className="text-gray-600 dark:text-gray-300">Date: Jan 22, 2024</p>
              <div className="mt-4 flex space-x-2">
                <Button size="sm" variant="outline">
                  Edit
                </Button>
                <Button size="sm" variant="outline">
                  Delete
                </Button>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="w-full sm:w-1/2 lg:w-1/3 p-4">
          <Card className="pt-5">
            <CardContent className="opacity-0 hover:opacity-100 transition-opacity duration-300">
              <h2 className="text-xl font-semibold mb-2">Fourth Post</h2>
              <p className="text-gray-600 dark:text-gray-300">Author: Lisa White</p>
              <p className="text-gray-600 dark:text-gray-300">Date: Jan 23, 2024</p>
              <div className="mt-4 flex space-x-2">
                <Button size="sm" variant="outline">
                  Edit
                </Button>
                <Button size="sm" variant="outline">
                  Delete
                </Button>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="w-full sm:w-1/2 lg:w-1/3 p-4">
          <Card className="pt-5">
            <CardContent className="opacity-0 hover:opacity-100 transition-opacity duration-300">
              <h2 className="text-xl font-semibold mb-2">Fifth Post</h2>
              <p className="text-gray-600 dark:text-gray-300">Author: Michael Brown</p>
              <p className="text-gray-600 dark:text-gray-300">Date: Jan 24, 2024</p>
              <div className="mt-4 flex space-x-2">
                <Button size="sm" variant="outline">
                  Edit
                </Button>
                <Button size="sm" variant="outline">
                  Delete
                </Button>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
      <footer className="p-6">
        <Pagination>
          <PaginationContent>
            <PaginationItem>
              <PaginationPrevious href="#" />
            </PaginationItem>
            <PaginationItem>
              <PaginationLink href="#">1</PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationLink href="#" isActive>
                2
              </PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationLink href="#">3</PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationEllipsis />
            </PaginationItem>
            <PaginationItem>
              <PaginationNext href="#" />
            </PaginationItem>
          </PaginationContent>
        </Pagination>
      </footer>
    </div>
  )
}
